### ISSUE TITLE
When instruments have the same name, the instrument editor gets confused

### ISSUE THREAD

**Issue by SolraBizna** [AdmiralPotato/ars-tracker#4]
Steps to reproduce:

1. New document, Instrument List and Instrument Editor open
2. Add instrument
3. Select instrument 0
4. Select Waveform
5. Change from 48 to 4
6. Select instrument 1
7. Graph is correct, text field is not

The actual data appears to be correct at this point, but subsequent confusion creates big problems in the editor, easily leading to accidental corruption of instruments.

**Comment by AdmiralPotato** [comment]
Looks like this was solved along side #2 with commit bd2d4fa580473c2cf6d86b3c54650d5353041704.
